# First steps of cleaning and preparing game dataset

In [4]:
import numpy as np
import matplotlib as plt
import pandas as pd

In [ ]:
raw_data = pd.read_csv(
    "../data/raw/games.csv",
    index_col=0
)
raw_data.head()

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,DiscountDLC count,About the game,Supported languages,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,[],...,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",['English'],...,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...","['English', 'French', 'German', 'Russian']",...,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN
3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",['Korean'],...,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,['English'],...,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN

In [20]:
# checking columns
raw_data.columns

Index(['AppID', 'Name', 'Release date', 'Estimated owners', 'Peak CCU',
       'Required age', 'Price', 'DiscountDLC count', 'About the game',
       'Supported languages', 'Full audio languages', 'Reviews',
       'Header image', 'Website', 'Support url', 'Support email', 'Windows',
       'Mac', 'Linux', 'Metacritic score', 'Metacritic url', 'User score',
       'Positive', 'Negative', 'Score rank', 'Achievements', 'Recommendations',
       'Notes', 'Average playtime forever', 'Average playtime two weeks',
       'Median playtime forever', 'Median playtime two weeks', 'Developers',
       'Publishers', 'Categories', 'Genres', 'Tags', 'Screenshots', 'Movies'],
      dtype='str')

In [22]:
# trying to fix index and column shift
raw_data.index.name
raw_data.iloc[0, :8]
raw_data[['AppID', 'Name', 'Release date', 'Estimated owners', 'Peak CCU', 'Required age', 'Price']].head()

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price
2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0
496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65
1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0
3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0
3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0

In [ ]:
#rereading in the data
raw_data = pd.read_csv(
    "../data/raw/games.csv",
    header=0,
    index_col=False,
    low_memory=False
)

raw_data.head()

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,DiscountDLC count,About the game,Supported languages,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...
1,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",...,8,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...
2,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...",...,0,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",...,0,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...
4,3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,...,0,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...

So the first few columns got fixed while the others became messed up, going to reload the data again

In [ ]:
#trying to reload data again
raw_data = pd.read_csv(
    "../data/raw/games.csv",
    engine="python",
    quotechar='"',
    sep=",",
    on_bad_lines="skip"
)

raw_data.head()

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,DiscountDLC count,About the game,Supported languages,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,[],...,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",['English'],...,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...","['English', 'French', 'German', 'Russian']",...,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN
3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",['Korean'],...,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,['English'],...,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN

Clearly this isnt fixing it so i will define what columns to pull, i believe there were some labeling issues when creating the data so i will pull what i think i need and adjust if necessary

In [33]:
print(raw_data.columns.tolist())

['AppID', 'Name', 'Release date', 'Estimated owners', 'Peak CCU', 'Required age', 'Price', 'Supported languages', 'Windows', 'Mac', 'Linux', 'Metacritic score', 'User score', 'Positive', 'Negative', 'Score rank', 'Achievements', 'Recommendations', 'Average playtime forever', 'Median playtime forever', 'Developers', 'Publishers', 'Categories', 'Genres']

In [ ]:
cols = [
    "AppID",
    "Name",
    "Release date",
    "Estimated owners",
    "Peak CCU",
    "Required age",
    "Price",
    "Supported languages",
    "Windows",
    "Mac",
    "Linux",
    "Metacritic score",
    "User score",
    "Positive",
    "Negative",
    "Score rank",
    "Achievements",
    "Recommendations",
    "Average playtime forever",
    "Median playtime forever",
    "Developers",
    "Publishers",
    "Genres",
    "Categories"
]

raw_data = pd.read_csv(
    "../data/raw/games.csv",
    usecols=cols,
    engine="python"
)
raw_data.head()

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,Supported languages,Windows,Mac,...,Negative,Score rank,Achievements,Recommendations,Average playtime forever,Median playtime forever,Developers,Publishers,Categories,Genres
2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,[],True,False,...,0,NaN,0,0,0,0,NaN,NaN,NaN,NaN
496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,['English'],True,False,...,3,NaN,0,231,8,8,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure
1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,"['English', 'French', 'German', 'Russian']",True,True,...,3,NaN,0,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual
3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,['Korean'],True,False,...,0,NaN,19,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation"
3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,['English'],True,False,...,0,NaN,0,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access"

In [36]:
for col in raw_data.columns:
  print(raw_data[col])

2539430               Black Dragon Mage Playtest
496350     Supipara - Chapter 1 Spring Has Come!
1034400        Mystery Solitaire The Black Raven
3292190              버튜버 파라노이아 - Vtuber Paranoia
3631080                            Maze Quest VR
                           ...
4152910                                     完美传奇
4042800           Poker Fate - ACG Texas Hold'em
3522550                          Adira Nusantara
3680350                       A Lenda de Niterói
4141790                            [BEAT:KEEPER]
Name: AppID, Length: 122611, dtype: str
2539430     Aug 1, 2023
496350     Jul 29, 2016
1034400     May 6, 2019
3292190    Oct 31, 2024
3631080    Apr 24, 2025
               ...
4152910     Jan 4, 2026
4042800     Jan 3, 2026
3522550     Jan 3, 2026
3680350     Jan 4, 2026
4141790     Jan 5, 2026
Name: Name, Length: 122611, dtype: str
2539430        0 - 0
496350     0 - 20000
1034400    0 - 20000
3292190    0 - 20000
3631080    0 - 20000
             ...
4152910        0 - 0
4042800        0 - 0
3522550        0 - 0
3680350        0 - 0
4141790        0 - 0
Name: Release date, Length: 122611, dtype: str
2539430    0
496350     0
1034400    0
3292190    1
3631080    0
          ..
4152910    0
4042800    0
3522550    0
3680350    0
4141790    0
Name: Estimated owners, Length: 122611, dtype: int64
2539430    0
496350     0
1034400    0
3292190    0
3631080    0
          ..
4152910    0
4042800    0
3522550    0
3680350    0
4141790    0
Name: Peak CCU, Length: 122611, dtype: int64
2539430    0.00
496350     5.24
1034400    4.99
3292190    8.99
3631080    4.99
           ...
4152910    0.00
4042800    0.00
3522550    7.99
3680350    2.09
4141790    0.00
Name: Required age, Length: 122611, dtype: float64
2539430     0
496350     65
1034400     0
3292190     0
3631080     0
           ..
4152910     0
4042800     0
3522550     0
3680350     0
4141790     0
Name: Price, Length: 122611, dtype: int64
2539430                                                   []
496350                                           ['English']
1034400           ['English', 'French', 'German', 'Russian']
3292190                                           ['Korean']
3631080                                          ['English']
                                 ...
4152910        ['Simplified Chinese', 'Traditional Chinese']
4042800    ['English', 'Japanese', 'Simplified Chinese', ...
3522550                                          ['English']
3680350                   ['Portuguese - Brazil', 'English']
4141790                              ['Japanese', 'English']
Name: Supported languages, Length: 122611, dtype: str
2539430    True
496350     True
1034400    True
3292190    True
3631080    True
           ...
4152910    True
4042800    True
3522550    True
3680350    True
4141790    True
Name: Windows, Length: 122611, dtype: bool
2539430    False
496350     False
1034400     True
3292190    False
3631080    False
           ...
4152910    False
4042800    False
3522550    False
3680350    False
4141790    False
Name: Mac, Length: 122611, dtype: bool
2539430    False
496350     False
1034400    False
3292190    False
3631080    False
           ...
4152910    False
4042800    False
3522550    False
3680350    False
4141790    False
Name: Linux, Length: 122611, dtype: bool
2539430    0
496350     0
1034400    0
3292190    0
3631080    0
          ..
4152910    0
4042800    0
3522550    0
3680350    0
4141790    0
Name: Metacritic score, Length: 122611, dtype: int64
2539430    0
496350     0
1034400    0
3292190    0
3631080    0
          ..
4152910    0
4042800    0
3522550    0
3680350    0
4141790    0
Name: User score, Length: 122611, dtype: int64
2539430      0
496350     252
1034400     21
3292190      0
3631080      0
          ...
4152910      0
4042800      0
3522550      0
3680350      0
4141790      0
Name: Positive, Length: 122611, dtype: int64
2539430    0
496350     3
1034400    3
3292190    0
3631080    0
          ..
4152910    0
4042800    0
3522550    0
3680350    0
4141790    0
Name: Negative, Length: 122611, dtype: int64
2539430   NaN
496350    NaN
1034400   NaN
3292190   NaN
3631080   NaN
           ..
4152910   NaN
4042800   NaN
3522550   NaN
3680350   NaN
4141790   NaN
Name: Score rank, Length: 122611, dtype: float64
2539430     0
496350      0
1034400     0
3292190    19
3631080     0
           ..
4152910     0
4042800     0
3522550     0
3680350     0
4141790     0
Name: Achievements, Length: 122611, dtype: int64
2539430      0
496350     231
1034400      0
3292190      0
3631080      0
          ...
4152910      0
4042800      0
3522550      0
3680350      0
4141790      0
Name: Recommendations, Length: 122611, dtype: int64
2539430    0
496350     8
1034400    0
3292190    0
3631080    0
          ..
4152910    0
4042800    0
3522550    0
3680350    0
4141790    0
Name: Average playtime forever, Length: 122611, dtype: int64
2539430    0
496350     8
1034400    0
3292190    0
3631080    0
          ..
4152910    0
4042800    0
3522550    0
3680350    0
4141790    0
Name: Median playtime forever, Length: 122611, dtype: int64
2539430                               NaN
496350                             minori
1034400                       Somer Games
3292190                             유진게임즈
3631080              Reality Expanded LLC
                        ...
4152910                              完美传奇
4042800    ©7 Points Digital Tech Limited
3522550                  Arraubi Gameware
3680350                       Seven Moons
4141790               Vantan Game Academy
Name: Developers, Length: 122611, dtype: str
2539430                               NaN
496350                         MangaGamer
1034400                            8floor
3292190                             유진게임즈
3631080              Reality Expanded LLC
                        ...
4152910                              完美传奇
4042800    ©7 Points Digital Tech Limited
3522550                  Arraubi Gameware
3680350                       Seven Moons
4141790               Vantan Game Academy
Name: Publishers, Length: 122611, dtype: str
2539430                                                  NaN
496350     Single-player,Steam Trading Cards,Steam Cloud,...
1034400                         Single-player,Family Sharing
3292190      Single-player,Steam Achievements,Family Sharing
3631080    Single-player,VR Only,Steam Leaderboards,Famil...
                                 ...
4152910    Single-player,Multi-player,MMO,PvP,Online PvP,...
4042800    Multi-player,PvP,Online PvP,Cross-Platform Mul...
3522550    Single-player,Custom Volume Controls,Narrated ...
3680350    Single-player,Full controller support,Family S...
4141790             Single-player,Partial Controller Support
Name: Categories, Length: 122611, dtype: str
2539430                                                  NaN
496350                                             Adventure
1034400                                               Casual
3292190                              Casual,Indie,Simulation
3631080                                  Action,Early Access
                                 ...
4152910    Action,Adventure,Massively Multiplayer,RPG,Sim...
4042800                         Casual,Strategy,Free To Play
3522550                 Action,Adventure,Casual,Early Access
3680350                        Action,Adventure,Casual,Indie
4141790                            Action,Indie,Free To Play
Name: Genres, Length: 122611, dtype: str

So what we are seeing is:
AppID -> Name
Name -> Release data
Release date -> Estimated owners
Estimated owners -> ...

UPDATE: I checked the discussions on kaggle for this dataset and someone mightve found the solution, will test now.

In [5]:
# testing solution found on discussion forum

cols = [
    "AppID",
    "Name",
    "Release date",
    "Estimated owners",
    "Peak CCU",
    "Required age",
    "Price",
    "DLC count",
    "Supported languages",
    "Windows",
    "Mac",
    "Linux",
    "Metacritic score",
    "User score",
    "Positive",
    "Negative",
    "Achievements",
    "Recommendations",
    "Average playtime forever",
    "Median playtime forever",
    "Developers",
    "Publishers",
    "Genres",
    "Categories"
]

raw_data = pd.read_csv(
    "../data/raw/games.csv",
    usecols=cols,
    engine="python"
)
raw_data.head()

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,DLC count,Supported languages,Windows,...,Positive,Negative,Achievements,Recommendations,Average playtime forever,Median playtime forever,Developers,Publishers,Categories,Genres
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,[],True,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
1,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,0,['English'],True,...,252,3,0,231,8,8,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure
2,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,"['English', 'French', 'German', 'Russian']",True,...,21,3,0,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,1,['Korean'],True,...,0,0,19,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation"
4,3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,['English'],True,...,0,0,0,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access"

The fix i found worked from what it looks like, noticed a comma was missing between the "Discount" and "DLC count" columns which was causing it all to be off. Going to double check results to make sure data matches column names.

In [6]:
for col in raw_data.columns:
  print(raw_data[col].head(3))

0    2539430
1     496350
2    1034400
Name: AppID, dtype: int64
0               Black Dragon Mage Playtest
1    Supipara - Chapter 1 Spring Has Come!
2        Mystery Solitaire The Black Raven
Name: Name, dtype: str
0     Aug 1, 2023
1    Jul 29, 2016
2     May 6, 2019
Name: Release date, dtype: str
0        0 - 0
1    0 - 20000
2    0 - 20000
Name: Estimated owners, dtype: str
0    0
1    0
2    0
Name: Peak CCU, dtype: int64
0    0
1    0
2    0
Name: Required age, dtype: int64
0    0.00
1    5.24
2    4.99
Name: Price, dtype: float64
0    0
1    0
2    0
Name: DLC count, dtype: int64
0                                            []
1                                   ['English']
2    ['English', 'French', 'German', 'Russian']
Name: Supported languages, dtype: str
0    True
1    True
2    True
Name: Windows, dtype: bool
0    False
1    False
2     True
Name: Mac, dtype: bool
0    False
1    False
2    False
Name: Linux, dtype: bool
0    0
1    0
2    0
Name: Metacritic score, dtype: int64
0    0
1    0
2    0
Name: User score, dtype: int64
0      0
1    252
2     21
Name: Positive, dtype: int64
0    0
1    3
2    3
Name: Negative, dtype: int64
0    0
1    0
2    0
Name: Achievements, dtype: int64
0      0
1    231
2      0
Name: Recommendations, dtype: int64
0    0
1    8
2    0
Name: Average playtime forever, dtype: int64
0    0
1    8
2    0
Name: Median playtime forever, dtype: int64
0            NaN
1         minori
2    Somer Games
Name: Developers, dtype: str
0           NaN
1    MangaGamer
2        8floor
Name: Publishers, dtype: str
0                                                  NaN
1    Single-player,Steam Trading Cards,Steam Cloud,...
2                         Single-player,Family Sharing
Name: Categories, dtype: str
0          NaN
1    Adventure
2       Casual
Name: Genres, dtype: str

Now that i have the data formatted and the columns i want, i can start cleaning

In [ ]:
selected_data = raw_data.copy()
selected_data.head()

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,DLC count,Supported languages,Windows,...,Positive,Negative,Achievements,Recommendations,Average playtime forever,Median playtime forever,Developers,Publishers,Categories,Genres
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,[],True,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
1,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,0,['English'],True,...,252,3,0,231,8,8,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure
2,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,"['English', 'French', 'German', 'Russian']",True,...,21,3,0,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,1,['Korean'],True,...,0,0,19,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation"
4,3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,['English'],True,...,0,0,0,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access"

In [8]:
# putting release date in datetime format

selected_data['Release date'] = pd.to_datetime(selected_data['Release date'], errors='coerce')
print(selected_data['Release date'])

0        2023-08-01
1        2016-07-29
2        2019-05-06
3        2024-10-31
4        2025-04-24
            ...
122606   2026-01-04
122607   2026-01-03
122608   2026-01-03
122609   2026-01-04
122610   2026-01-05
Name: Release date, Length: 122611, dtype: datetime64[us]

In [ ]:
#cleaning out all games with 0-0 estimated owners
selected_data = selected_data[selected_data['Estimated owners'] != '0 - 0']
print(selected_data['Estimated owners'])

1               0 - 20000
2               0 - 20000
3               0 - 20000
4               0 - 20000
5               0 - 20000
               ...
122558          0 - 20000
122572      20000 - 50000
122573      20000 - 50000
122593    100000 - 200000
122601          0 - 20000
Name: Estimated owners, Length: 100970, dtype: str

In [16]:
#creating midpoint column for owners, and sorting df by that midpoint
owner_split = selected_data['Estimated owners'].str.split(' - ', expand=True)

selected_data["owners_low"] = pd.to_numeric(owner_split[0])
selected_data["owners_high"] = pd.to_numeric(owner_split[1])

selected_data["owners_mid"] = (selected_data["owners_low"] + selected_data["owners_high"]) / 2

In [19]:
sorted_owner_data = selected_data.sort_values(by = 'owners_mid')
sorted_owner_data.tail(10)

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,DLC count,Supported languages,Windows,...,Recommendations,Average playtime forever,Median playtime forever,Developers,Publishers,Categories,Genres,owners_low,owners_high,owners_mid
110911,550,Left 4 Dead 2,2009-11-16,50000000 - 100000000,25122,0,1.99,0,"['Danish', 'Dutch', 'English', 'Finnish', 'Fre...",True,...,770930,2316,540,Valve,Valve,"Single-player,Multi-player,PvP,Online PvP,Co-o...",Action,50000000,100000000,75000000.0
105321,1063730,New World: Aeternum,2021-09-28,50000000 - 100000000,5583,0,59.99,2,"['English', 'French', 'Italian', 'German', 'Sp...",True,...,253342,10500,3781,Amazon Games,Amazon Games,"Multi-player,MMO,PvP,Online PvP,Co-op,Online C...","Action,Adventure,Massively Multiplayer,RPG",50000000,100000000,75000000.0
44134,2358720,Black Myth: Wukong,2024-08-19,50000000 - 100000000,15004,13,59.99,2,"['English', 'French', 'German', 'Spanish - Spa...",True,...,863021,3272,2812,Game Science,Game Science,"Single-player,Steam Achievements,Full controll...","Action,Adventure,RPG",50000000,100000000,75000000.0
85553,304930,Unturned,2017-07-07,50000000 - 100000000,10408,0,0.00,1,['English'],True,...,7544,8683,320,Smartly Dressed Games,Smartly Dressed Games,"Single-player,Multi-player,PvP,Online PvP,LAN ...","Action,Adventure,Casual,Indie,Free To Play",50000000,100000000,75000000.0
57377,440,Team Fortress 2,2007-10-10,50000000 - 100000000,43819,0,0.00,1,"['English', 'Danish', 'Dutch', 'Finnish', 'Fre...",True,...,45622,23093,4262,Valve,Valve,"Multi-player,Cross-Platform Multiplayer,Steam ...","Action,Free To Play",50000000,100000000,75000000.0
27431,1938090,Call of Duty®,2022-10-27,50000000 - 100000000,67419,17,0.00,43,"['English', 'French', 'Italian', 'German', 'Sp...",True,...,402945,5485,717,"Treyarch,Raven Software,Beenox,High Moon Studi...",Activision,"Single-player,Multi-player,PvP,Online PvP,Co-o...",Action,50000000,100000000,75000000.0
45509,730,Counter-Strike 2,2012-08-21,100000000 - 200000000,1013936,0,0.00,1,"['Czech', 'Danish', 'Dutch', 'English', 'Finni...",True,...,4830455,33906,6237,Valve,Valve,"Multi-player,Cross-Platform Multiplayer,Steam ...","Action,Free To Play",100000000,200000000,150000000.0
4193,570,Dota 2,2013-07-09,100000000 - 200000000,623941,0,0.00,2,"['Bulgarian', 'Czech', 'Danish', 'Dutch', 'Eng...",True,...,14369,54064,1155,Valve,Valve,"Multi-player,Co-op,Steam Trading Cards,Steam W...","Action,Strategy,Free To Play",100000000,200000000,150000000.0
54502,1172470,Apex Legends™,2020-11-04,100000000 - 200000000,124262,0,0.00,0,"['English', 'French', 'Italian', 'German', 'Sp...",True,...,1572,10073,916,Respawn,Electronic Arts,"Multi-player,PvP,Online PvP,Co-op,Online Co-op...","Action,Adventure,Free To Play",100000000,200000000,150000000.0
8878,578080,PUBG: BATTLEGROUNDS,2017-12-21,100000000 - 200000000,314682,13,0.00,0,"['English', 'Korean', 'Simplified Chinese', 'F...",True,...,1753261,23787,6082,PUBG Corporation,"KRAFTON, Inc.","Multi-player,PvP,Online PvP,Stats,Remote Play ...","Action,Adventure,Massively Multiplayer,Free To...",100000000,200000000,150000000.0